import "./globals.css";
// import { Roboto } from "next/font/google";
import { UserProvider } from "./context/userContext";

// const roboto = Roboto({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <UserProvider>
      <html lang="en">
        <body>{children}</body>
      </html>
    </UserProvider>
  );
}
