import "./globals.css";
import { Inter } from "next/font/google";
import { UserProvider } from "./context/userContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <UserProvider>
      <html lang="en">
        <body className={inter.className}>
          <style>
            {`
          body::-webkit-scrollbar {
            display: none;
          }
        `}
          </style>
          {children}
        </body>
      </html>
    </UserProvider>
  );
}
